#pragma once

#include <vector>
#include <memory>

#include "../WaveFunctions/wavefunctioncache.h"

class MonteCarlo {
public:
    MonteCarlo(std::unique_ptr<class Random> rng);
    // Use the default deconstructor generated by the compiler
    virtual ~MonteCarlo() = default;

    virtual bool step(
            double stepParameter,
            class WaveFunction& waveFunction,
        std::vector<std::unique_ptr<class Particle>>& particles) = 0;
    virtual bool hasAnalyticalOption() = 0;
    virtual bool get_preferAnalytic() = 0;
    WaveFunctionCache& getCache() { return *m_cache; }

protected:
    std::unique_ptr<class Random> m_rng;
    std::unique_ptr<WaveFunctionCache> m_cache;
};
