#pragma once
#include <memory>
#include <vector>

class Hamiltonian {
public:
    // Use the default deconstructor generated by the compiler
    virtual ~Hamiltonian() = default;
    virtual double computeLocalEnergy(
            class WaveFunction& waveFunction,
            std::vector<std::unique_ptr<class Particle>>& particles
    ) = 0;
    void set_analytic_ifAvailable(bool val);
    virtual double getRepulsiveFactor() const { return 0.0; }
protected:
    bool m_analytic_ifAvailable = true;
};

